package net.earthcomputer.clientcommands.features;

import com.seedfinding.latticg.math.component.BigMatrix;
import com.seedfinding.latticg.math.component.BigVector;
import com.seedfinding.latticg.math.lattice.enumerate.EnumerateRt;
import com.seedfinding.latticg.math.optimize.Optimize;
import com.seedfinding.latticg.util.DeserializeRt;
import java.util.stream.LongStream;

// CLASS GENERATED BY LATTICG, DO NOT EDIT MANUALLY
public final class CCrackRngGenPaper {
    private CCrackRngGenPaper() {}
    private static final BigMatrix BASIS = DeserializeRt.mat(
        "ਊ鏲\uf7b7蠍ʖ袈뎎簂\ud8e3璘銰Ă﮶蚴샠Ă얩싞\uf3a2Ă\ud8c1쪜鎐Ă꪿얆ꁢˊ\ue5bd삺윁ʈ\udfd4\ue5af\ue304ʘ鯋\udf91㴂쎝ﮁ蘴˛쮓뮫送ʘ\udcc3톐젃ʖ쫊늇⨂\udc81쟦앴˩\uf591飤㈂\ue7b8" +
        "잟쩤ˇﲸ\uf1c4ἂ좨铉돋Ȃꦸ\uf6a5閉Ă\uf399ﶏ酈ʶ쏜\udebe㨂\ud8a0\ueaa5\ueab4Ȃꚦꎹ쵗ʅ열욾눂˘麕\uecce宅˷돾쇉市ퟑ\udd90\ue2eeȂ囹\uec87턱˩\udfc1쎅됃ʣﾸ\ue8d8㜂뮂맜雲Ȃ飑" +
        "\uebea臤Ă뛥냨\ud966˥귢횻锁ʘ鿦苧㘂徭\udca7쒚̂骞\ueeb5옴ʹ룂ꮻꌁʩ뮮춢씂˓ꖖ\ude94蠁˖\uead7몯考ʩ\uf2e3ꋺ\uf501ˆ쾹\ue6cc輂ʼ鞏\ue4a2㐂꧔\ue2cc뻢Ă\ueaec뗉\ud9abĂ請쎯\udb97" +
        "Ȃ廉膇쎗Ă\ue9aa軵얓Ăﻚꪩ렿ʛ귃쫆ਂ飶뗀\uf580Ȃꮓﺨ뫅Ă\udcda\ud8cf鰱ʘ\ue49c\uefe0밁˚룫觷ꈃ˺\uecb1뢔밂ʹ覊뛁圂\ud8f1ꊛ괮ˎꪥ螓㴂诂랖\udce5Ă꧕雖론˦蒏賝ᜂ薔ﻝ캢Ă\ud8e8ﲱꢗȂ랞\udc9a" +
        "ﳸĂ\ueafb\udad7뎓Ȃ曆\udcb1\ue23e˩얰黐︁ˣ캛覛븁˻讈캫訁ʘ쯬際⌂诠뎳젡˥\ue4f6\uf792匂飙鯊슋Ă쟠뎦艁˚꾯醞崂맊\ue4d5뺉Ă\ud8ceퟦ\ue6dbȂ鏩꧌쬫ʖ\ufdd4룋\ue401˘\uf78b훵㠂ﯹ\uf1de" +
        "\ue6c9Ђ엇\uf3af菏Ăꦪ튨헄Ȃꫪ뒁髄Ă쪀쫪\uf8bdĂ理캭钡Ȃ\ue9b0\uded3\ueab5Ă쎼\udfd0휛ʦꆻ鮁뼂˩꿆\uf4b1먁ʖ뿶즰㌂\udc93냫뢛Ԃ\ue981뎾\uf31d˧薴돯\uea02ˇ\ud993邑섂ˈ蒬타餁" +
        "ʩꓖ퇩䠂");
    private static final BigMatrix ROOT_INV = DeserializeRt.mat(
        "ਊ⮀肀肀肀Ă肀肀肀䀃肀肀肀䁇肀肀肀老ྀ肀肀聀ڀ肀肀耐ڀ肀肀肀ţ肀肀肀老ހ肀肀耠ހ肀肀耐ހ肀肀肀Ă肀肀肀 肀肀肀″肀肀肀老Ẁ肀肀肀Ċ肀肀肀䀓肀肀肀老\u0380肀肀耐ʀ肀肀聀ހ肀肀聀⎀肀肀肀ł肀肀肀老ʀ肀肀耐⮀肀肀肀Ć肀肀肀老ʀ肀肀耈ྀ肀肀肀ă肀肀肀䀂" +
        "肀肀肀老ྀ肀肀聀ក肀肀肀Ė肀肀肀老ڀ肀肀肀ē肀肀肀老ʀ肀肀耈ʀ肀肀肀ă肀肀肀\u200f肀肀肀老ᎀ肀肀聀ྀ肀肀聀ހ肀肀肀Ă肀肀肀䀏肀肀肀老ኀ肀肀肀ă肀肀肀䀎肀肀肀䀆肀肀肀老ʀ肀肀耠\u0380肀肀聀 肀肀聀\u0e80肀肀肀ď肀肀肀䀊肀肀肀䀂肀肀肀䀇" +
        "肀肀肀老᪀肀肀肀Ď肀肀肀老ʀ肀肀耐ྀ肀肀肀Ē肀肀肀老 肀肀肀ē肀肀肀䀃肀肀肀䀖肀肀肀䀀Ȇ肀肀肀䀟肀肀肀老\u0380肀肀耠\u0380肀肀耠ʀ肀肀耠\2 肀肀肀ď肀肀肀老ᎀ肀肀肀Ě肀肀肀老᪀肀肀肀Ħ肀肀肀老ʀ肀肀耠\2\u0380肀肀耠ڀ肀肀耐ހ肀肀" +
        "肀ċ肀肀肀老\u0a80肀肀聀\u0380肀肀聀ក肀肀肀ă肀肀肀老\u0380肀肀耠\u0b80肀肀肀Ċ肀肀肀老\u0380肀肀耠\u0380肀肀肀ć肀肀肀老\u0380肀肀耈\u0380肀肀耠\u0e80肀肀肀ć肀肀肀‖肀肀肀老\u0380肀肀耐\u0b80" +
        "肀肀聀");
    private static final BigVector ORIGIN = DeserializeRt.vec(
        "\u0a00ˌ\ue598궋\udb48ʸꆽ\uaaf8葉˄즔躈昂\uf083\uda8c틡㘂벆胐퇙朂ꢗ鯑黪朂뒌헒짍㠂\ue0cbꟛ銝漂곋龹\ud7fd㠂");
    private static final BigVector ROOT_ORIGIN = DeserializeRt.vec(
        "\u0adf뚂\uf1e0뭬肀肀肀Ң짽躟쓭ր肀肀聀昄\udfb6英\ue0bb쨁肀肀肀ზ醌뗤\uaafcঀ肀肀聀\udeb6英\ue0bb\ue201肀肀肀ိ˖醌뗤ꫬႀ肀肀聀ꏉﶎ鿄봉肀肀肀䃗醌뗤ꪬހ肀肀聀");

    /**
     * Finds all values of {@code seed} that could produce the given results in the following code:
     * <pre>{@code
     *    Random rand = new Random(seed ^ 0x5DEECE66DL);
     *    // Go backwards by 139 random calls
     *    float nextFloat1 = rand.nextFloat();
     *    assert nextFloat1 >= minNextFloat1 && nextFloat1 < maxNextFloat1;
     *    // Skip 13 random calls
     *    float nextFloat2 = rand.nextFloat();
     *    assert nextFloat2 >= minNextFloat2 && nextFloat2 < maxNextFloat2;
     *    // Skip 13 random calls
     *    float nextFloat3 = rand.nextFloat();
     *    assert nextFloat3 >= minNextFloat3 && nextFloat3 < maxNextFloat3;
     *    // Skip 13 random calls
     *    float nextFloat4 = rand.nextFloat();
     *    assert nextFloat4 >= minNextFloat4 && nextFloat4 < maxNextFloat4;
     *    // Skip 13 random calls
     *    float nextFloat5 = rand.nextFloat();
     *    assert nextFloat5 >= minNextFloat5 && nextFloat5 < maxNextFloat5;
     *    // Skip 13 random calls
     *    float nextFloat6 = rand.nextFloat();
     *    assert nextFloat6 >= minNextFloat6 && nextFloat6 < maxNextFloat6;
     *    // Skip 13 random calls
     *    float nextFloat7 = rand.nextFloat();
     *    assert nextFloat7 >= minNextFloat7 && nextFloat7 < maxNextFloat7;
     *    // Skip 13 random calls
     *    float nextFloat8 = rand.nextFloat();
     *    assert nextFloat8 >= minNextFloat8 && nextFloat8 < maxNextFloat8;
     *    // Skip 13 random calls
     *    float nextFloat9 = rand.nextFloat();
     *    assert nextFloat9 >= minNextFloat9 && nextFloat9 < maxNextFloat9;
     *    // Skip 13 random calls
     *    float nextFloat10 = rand.nextFloat();
     *    assert nextFloat10 >= minNextFloat10 && nextFloat10 < maxNextFloat10;
     * }</pre>
     *
     * <p>This code skips 0,000000% of seeds in its search.
     */
    public static LongStream getSeeds(float minNextFloat1, float maxNextFloat1, float minNextFloat2, float maxNextFloat2, float minNextFloat3, float maxNextFloat3, float minNextFloat4, float maxNextFloat4, float minNextFloat5, float maxNextFloat5, float minNextFloat6, float maxNextFloat6, float minNextFloat7, float maxNextFloat7, float minNextFloat8, float maxNextFloat8, float minNextFloat9, float maxNextFloat9, float minNextFloat10, float maxNextFloat10) {
        Optimize.Builder builder = Optimize.Builder.ofSize(10);
        if (minNextFloat1 >= maxNextFloat1) {
            return LongStream.empty();
        }
        builder.withLowerBound(0, (long) (minNextFloat1 * 0x1.0p24f) << 24).withUpperBound(0, (long) (maxNextFloat1 * 0x1.0p24f) << 24);
        if (minNextFloat2 >= maxNextFloat2) {
            return LongStream.empty();
        }
        builder.withLowerBound(1, (long) (minNextFloat2 * 0x1.0p24f) << 24).withUpperBound(1, (long) (maxNextFloat2 * 0x1.0p24f) << 24);
        if (minNextFloat3 >= maxNextFloat3) {
            return LongStream.empty();
        }
        builder.withLowerBound(2, (long) (minNextFloat3 * 0x1.0p24f) << 24).withUpperBound(2, (long) (maxNextFloat3 * 0x1.0p24f) << 24);
        if (minNextFloat4 >= maxNextFloat4) {
            return LongStream.empty();
        }
        builder.withLowerBound(3, (long) (minNextFloat4 * 0x1.0p24f) << 24).withUpperBound(3, (long) (maxNextFloat4 * 0x1.0p24f) << 24);
        if (minNextFloat5 >= maxNextFloat5) {
            return LongStream.empty();
        }
        builder.withLowerBound(4, (long) (minNextFloat5 * 0x1.0p24f) << 24).withUpperBound(4, (long) (maxNextFloat5 * 0x1.0p24f) << 24);
        if (minNextFloat6 >= maxNextFloat6) {
            return LongStream.empty();
        }
        builder.withLowerBound(5, (long) (minNextFloat6 * 0x1.0p24f) << 24).withUpperBound(5, (long) (maxNextFloat6 * 0x1.0p24f) << 24);
        if (minNextFloat7 >= maxNextFloat7) {
            return LongStream.empty();
        }
        builder.withLowerBound(6, (long) (minNextFloat7 * 0x1.0p24f) << 24).withUpperBound(6, (long) (maxNextFloat7 * 0x1.0p24f) << 24);
        if (minNextFloat8 >= maxNextFloat8) {
            return LongStream.empty();
        }
        builder.withLowerBound(7, (long) (minNextFloat8 * 0x1.0p24f) << 24).withUpperBound(7, (long) (maxNextFloat8 * 0x1.0p24f) << 24);
        if (minNextFloat9 >= maxNextFloat9) {
            return LongStream.empty();
        }
        builder.withLowerBound(8, (long) (minNextFloat9 * 0x1.0p24f) << 24).withUpperBound(8, (long) (maxNextFloat9 * 0x1.0p24f) << 24);
        if (minNextFloat10 >= maxNextFloat10) {
            return LongStream.empty();
        }
        builder.withLowerBound(9, (long) (minNextFloat10 * 0x1.0p24f) << 24).withUpperBound(9, (long) (maxNextFloat10 * 0x1.0p24f) << 24);
        return EnumerateRt.enumerate(BASIS, ORIGIN, builder.build(), ROOT_INV, ROOT_ORIGIN)
            .mapToLong(vec -> (vec.get(0).getNumerator().longValue() * 0xca00ae6f089L + 0x635595522ac2L) & ((1L << 48) - 1));
    }
}
